name: 'Install CMake'
description: 'Download and configure CMake'
inputs:
  url:
    description: "URL of CMake bundle to download"
  hash:
    description: "Expected bundle hash"
  install_dir:
    description: "Location where to install the CMake bundle"
    default: /tmp/cmake

outputs:
  cmake:
    description: "Path to the installed CMake executable."
    value: ${{ steps.unpack-cmake.outputs.cmake-path }}
  ctest:
    description: "Path to the installed CMake ctest executable."
    value: ${{ steps.unpack-cmake.outputs.ctest-path }}
runs:
  using: "composite"
  steps:
    - name: Download CMake
      shell: bash
      env:
        CMAKE_URL: ${{ inputs.url }}
      run: |
        curl -Llo /tmp/cmake.tar.gz "$CMAKE_URL"
    - name: Verify CMake
      shell: bash
      env:
        CMAKE_HASH: ${{ inputs.hash }}
      run:
        echo "$CMAKE_HASH  /tmp/cmake.tar.gz" | shasum -a 256 -c-
    - name: Unpack CMake
      shell: bash
      id: unpack-cmake
      env:
        CMAKE_INSTALL_DIR: ${{ inputs.install_dir }}
      run: |
        mkdir "$CMAKE_INSTALL_DIR"
        tar xf /tmp/cmake.tar.gz --strip-components=1 -C "$CMAKE_INSTALL_DIR"
        echo "cmake-path=$CMAKE_INSTALL_DIR/bin/cmake" >> "$GITHUB_OUTPUT"
        echo "ctest-path=$CMAKE_INSTALL_DIR/bin/ctest" >> "$GITHUB_OUTPUT"
